name: "Demo workflow, runs on PR"

on: [pull_request]

jobs:
  tell_ref:
    name: "Display GITHUB_REF"
    runs-on: ubuntu-latest
    steps:
    - name: "Show GITHUB_REF"
      run: echo "$GITHUB_CONTEXT"

  echo_secret_correctly:
    name: "Display a secret and have it hidden"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is redacted by GitHub, will not appear"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}"      

  reveal_secret_uppercase:
    name: "Display a secret uppercase"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is NOT redacted, LEAKED to the log"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}".ToUpper()      

  reveal_secret_withbug:
    name: "Display a secret due to a bug"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is NOT redacted, LEAKED to the log"
      # Here I forget to use quotes
      # This will make the action fail because there is a quote in the secret string
      run: echo ${{secrets.NOT_TOO_CONFIDENTIAL}}
