name: "Demo workflow, runs on PR"

on: [pull_request]

jobs:
  tell_env_on_linux:
    name: "Show Workflow info, with Powershell on Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "Run echos"
        shell: pwsh
        run: |
        echo "GITHUB_WORKFLOW $env:GITHUB_WORKFLOW"
        
        # echo "GITHUB_RUN_ID ${env:GITHUB_RUN_ID}"
        # echo "GITHUB_RUN_NUMBER ${env:GITHUB_RUN_NUMBER}"
        # echo "GITHUB_ACTOR ${env:GITHUB_ACTOR}"
        # echo "GITHUB_EVENT_NAME ${env:GITHUB_EVENT_NAME}"
        # echo "GITHUB_EVENT_PATH ${env:GITHUB_EVENT_PATH}"
        # echo "GITHUB_WORKSPACE ${env:GITHUB_WORKSPACE}"
        # echo "GITHUB_SHA ${env:GITHUB_SHA}"
        # echo "GITHUB_REF ${env:GITHUB_REF}"
        # echo "NETCORE_VERSION ${env:NETCORE_VERSION}"

  tell_ref:
    name: "Display GITHUB_REF"
    runs-on: ubuntu-latest
    steps:
    - name: "Show GITHUB_REF"
      run: echo ${env:GITHUB_REF}
      shell: pwsh

  echo_secret_correctly:
    name: "Display a secret and have it hidden"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is redacted by GitHub, will not appear"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}"
      shell: pwsh

  reveal_secret_uppercase:
    name: "Display a secret uppercase"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is NOT redacted, LEAKED to the log"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}".ToUpper()      
      shell: pwsh

  reveal_secret_withbug:
    name: "Display a secret due to a bug"
    runs-on: ubuntu-latest
    steps:
    - name: "The secret is NOT redacted, LEAKED to the log"
      # Here I forget to use quotes
      # This will make the action fail because there is a quote in the secret string
      run: echo ${{secrets.NOT_TOO_CONFIDENTIAL}}
      shell: pwsh
