name: "Demo workflow, runs on push to main branch"

on:
  push:
    branches:    
      - master

jobs:
  singlejob:
    name: "Only job in this workflow"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Show GITHUB_REF"
      run: echo ${env:GITHUB_REF}

    - name: "Show a secret correctly: it gets redacted"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}"      

    - name: "Show a secret uppercased: **it gets shown**, DANGER"
      run: echo "${{secrets.NOT_TOO_CONFIDENTIAL}}".ToUpper()      

    - name: "Show a secret with an error in the script: **it gets shown**, DANGER"
      # Here I forget to use quotes
      # This will make the action fail because there is a quote in the secret string
      run: echo ${{secrets.NOT_TOO_CONFIDENTIAL}}
